### PR TITLE
Bg responsive header

### PR DESCRIPTION
**Pull request by jamsgra**
#### What does this PR do?
Adds responsiveness to the MainHeader & the title of ArticleLarge, & makes the ArticleGrid images all same size. Also removed comments/commented out code.

### CODE REVIEW

**Comment by djordjijem** [comment]
make it <992px one button one line..its clumsy like this xD so basicaly it will take the whole screen

**Review by janselme — APPROVED** [review]

**Comment by djordjijem** [comment]
...

**Comment by djordjijem** [comment]
Can't do it from phone :(

**Review by djordjijem — APPROVED** [review]

**Comment by djordjijem** [comment]
I.can xD

**Pull request merged**
