### PR TITLE
#13 Feature: Limit char content in card Grid

### PR DESCRIPTION
**Pull request by janselme**
Not proud of how I handled it.
If you have a better solution...

### CODE REVIEW

**Review by djordjijem — APPROVED** [review]
Can we do it without [ ]s ? If not leave don't bother

**Comment by janselme** [comment]
@djordjijem Done

**Review by jamsgra — CHANGES_REQUESTED** [review]
Hey so at the moment the text ends abruptly: 

Screen Shot 2019-04-27 at 12 33 52

So I would suggest having '...' after to avoid it looking strange (without the square brackets).

**Comment by janselme** [comment]
@jamsgra Done

**Review by jamsgra — APPROVED** [review]

**Pull request merged**
