### PR TITLE
Feature: Add search & 404 route, fix bug for no results

### PR DESCRIPTION
**Pull request by jamsgra**
#### What does this PR do?
It adds new routes to the page:

- A 404 page if an incorrect route is entered

- A search route to handle search queries

It also fixes a bug when no search results are returned from the news api, showing a 'No results returned' message instead of causing an error.

#### How should this be manually tested?
Make searches and check that they work correctly and produce no bugs.

#### Any background context you want to provide?
Uses react-router-dom alongside query-string to parse the search urls.

### CODE REVIEW

**Comment by djordjijem** [comment]
Can u combine the two..when there is bad request just do nothing (stay on loading screen, user will figure out himself immedietly and it will look like its trying to find it, on any input ;) ), when  success render the correct route and change the URL also ? There is simply too much unnecessary abstraction xD tnx

**Comment by jamsgra** [comment]
I'm not sure I understand what you mean.

The 404 route is triggered when a user types in a route in the web browser address bar that hasn't been defined, e.g '/food'.

The search route is triggered when a user submits a search in the top bar search form. If the news api returns valid results it will display them, otherwise it will say to the user "Sorry no results found."

**Comment by djordjijem** [comment]
I mean, on failure do nothing, change nothing, on success (on any string with success) render the new content and change the route. Example, user types food: it changes the route to ../food .

**Review by djordjijem — APPROVED** [review]
Excellent work.

**Review by janselme — APPROVED** [review]
Looking good!

**Pull request merged**
