### PR TITLE
Article Large component: static structure

### PR DESCRIPTION
**Pull request by janselme**
Hi,
With Abdul permission, I started his component.

Can you:
Run `npm install` if react-bootstrap is not installed
Then `npm start` to launch the project

To check:
- [ ] Responsive/CSS
- [ ] Component structure

Thanks!

### CODE REVIEW

**Comment by djordjijem** [comment]
Everything looks fine, responsivnes works correctly. @jamsgra  look how she used bootstrap ;)  Good job girl!

**Review by djordjijem — APPROVED** [review]
approved :dancing_men:

**Review by jamsgra — CHANGES_REQUESTED** [review]
It looks good though my only comment would be on layout, as the article size might be too big. I think it should fit on the screen and have white space at the bottom without having to scroll down to see the rest of it. Maybe removing some of the margin on the title at the top might help. What do you think?

Screen Shot 2019-04-11 at 13 39 00

**Comment by janselme** [comment]
Hi @jamsgra 
I changed some spacing. Can you take a look, please?
Thanks

**Review by jamsgra — APPROVED** [review]

**Pull request merged**
